'use strict';

var nicePhrases = [
  "As long as you think your past is bad you must be improving.",
  "Some people are crushed by misfortune, Others grow because of it.",
  "Bad day, not a bad life. There is always some good in a bad day.",
  "Don't cling to a mistake just because you spent a lot of time making it.",
  "If you can survive disappointment then nothing can beat you.",
  "A river cuts through rock, not because of its power, but because of its persistence.",
  "Work Hard in silence, let Success be your NOISE",
  "You will never lose. You will either win or learn.",
  "You know, sometimes all you need is 20 seconds of insane courage.",
  "Everything will be okay in the end. If it's not okay. it's not the end.",
  "these mountains that you are carrying, you were only supposed to climb.",
  "Work until you no longer have to Introduce Yourself",
  "The less you respond to negative people, the more peaceful your life will become.",
  "If we wait untill we're ready, we'll be waiting for the rest of our lives.",
  "If you get tired learn to rest, not to QUIT.",
  "If there is no wind, row.",
  "The World is against you. It wouldn't be fair otherwise.",
  "You can fail in life doing the things you hate so you might as well take a chance doing what you love",
  "Take the bricks your enemies throw at you and build a fucking castle.",
  "Do Something that your future self will thank you for",
  "Life is like a photograph you need the negatives to develop",
  "Once you've accepted your flaws, no one can use them against you.",
  "A comfort zone is a beautiful place, but nothing ever grows there.",
  "Sometimes when things are falling apart they may actually be falling into place.",
  "The bad news is time flies. The good news is you're the pilot.",
  "Your future self is watching you right now through your memories.",
  "Listen. I wish i could tell you it gets better. But, it doesn't get better. You get Better.",
  "You did not wake up today to be mediocre",
  "We cannot become what we need to be by remaining what we are.",
  "No such thing as free time. All you got is life time. Go.",
  "There is no elevator to success. You have to take the stairs.",
  "Some people die at 25 and aren't buried until 75.",
  "The trouble with most of us is that we would rather be ruined by praise than saved by criticism.",
  "The trouble is, you think you have time - Buddha",
  "Eight Per Cent of success is showing up.",
  "The greatest pleasure in life is doing what people say you cannot do.",
  "They tried to bury us. They didn't know we were seeds.",
  "I've had a lot of worries in my life, most of which never happened",
  "Listen, smile, agree, and then do whatever the fuck you were gonna do anyway.",
  "If it's not impossible, there must be a way to do it.",
  "Forgive others not because they deserve forgiveness but because you deserve peace.",
  "Do not believe the things you tell yourself when you are sad and lonely.",
  "Be willing to walk alone. Many who started with you won't finish with you."
  "If you want to achieve greatness stop asking for permission. - Anonymous",
"Things work out best for those who make the best of how things work out. - John Wooden",
"To live a creative life, we must lose our fear of being wrong. - Anonymous",
"If you are not willing to risk the usual you will have to settle for the ordinary. - Jim Rohn",
"Trust because you are willing to accept the risk, not because it’s safe or certain. - Anonymous",
"All our dreams can come true if we have the courage to pursue them. - Walt Disney",
"Good things come to people who wait, but better things come to those who go out and get them. - Anonymous",
"If you do what you always did, you will get what you always got. - Anonymous",
"Success is walking from failure to failure with no loss of enthusiasm. - Winston Churchill",
"Just when the caterpillar thought the world was ending, he turned into a butterfly. - Proverb",
"Successful entrepreneurs are givers and not takers of positive energy. - Anonymous",
"You know you're in love when you can't fall asleep because reality is finally better than your dreams. - Dr. Seuss",
"Whenever you see a successful person you only see the public glories, never the private sacrifices to reach them. - Vaibhav Shah",
"Don’t be afraid to give up the good to go for the great. - John D. Rockefeller",
"The distance between insanity and genius is measured only by success. - Bruce Feirstein",
"Don’t raise your voice, improve your argument. - Anonymous",
"What seems to us as bitter trials are often blessings in disguise. - Oscar Wilde",
"Do one thing every day that scares you. - Eleanor Roosevelt",
"What’s the point of being alive if you don’t at least try to do something remarkable. - Anonymous",
"Life is not about finding yourself. Life is about creating yourself. - Lolly Daskal",
"What lies behind us and what lies before us are tiny matters compared to what lies within us. - Ralph Waldo Emerson",
"It is never too late to be what you might have been. - George Eliot",
"Innovation distinguishes between a leader and a follower. - Steve Jobs",
"In three words I can sum up everything I've learned about life: it goes on. - Robert Frost",
"It does not matter how slowly you go, so long as you do not stop. - Confucius",
"We are still masters of our fate. We are still captains of our souls. - Winston Churchill",
"The best way out is always though. - Robert Frost",
"Hope is like the sun, which, as we journey toward it, casts the shadow of our burden behind us. - Samuel Smiles",
"Enthusiasm is the energy and force that builds literal momentum of the human soul and mind. - Bryant McGill",
"Sometimes thinking too much can destroy your momentum. - Tom Watson",
"Work spares us from three evils: boredom, vice, and need. - Voltaire",
"Fortune favors the brave. - Publius Terence",
"Strong lives are motivated by dynamic purposes. - Kenneth Hildebrand",
"Either write something worth reading or do something worth writing. - Benjamin Franklin",
"If the wind will not serve, take to the oars. - Latin Proverb",
"There are no traffic jams along the extra mile. - Roger Staubach",
"Too many of us are not living our dreams because we are living our fears. - Les Brown",
"Challenges are what make life interesting and overcoming them is what makes life meaningful. - Joshua J. Marine",
"I have been impressed with the urgency of doing. Knowing is not enough; we must apply. Being willing is not enough; we must do. - Leonardo da Vinci",
"Start where you are. Use what you have. Do what you can. - Arthur Ashe",
"Happiness is not something readymade. It comes from your own actions. - Dalai Lama",
"If you do what you’ve always done, you’ll get what you’ve always gotten. - Tony Robbins",
"If you are offered a seat on a rocket ship, don’t ask what seat! Just get on. - Sheryl Sandberg",
"The question isn’t who is going to let me; it’s who is going to stop me. - Ayn Rand",
"Always work hard. Intensity clarifies. It creates not only momentum, but also the pressure you need to feel either friction, or fulfillment. - Marcus Buckingham",
"We are what we repeatedly do. Excellence, therefore, is not an act but a habit. - Aristotle",
"Take calculated risks. That is quite different from being rash. - George S. Patton",
"In every difficult situation is potential value. Believe this, then begin looking for it. - Norman Vincent Peale",
"When everything seems to be going against you, remember that the airplane takes off against the wind, not with it. - Henry Ford",
"Accept responsibly for your life. Know that it is you who will get you where you want to go, no one else. - Les Brown",
"You cannot plough a field by turning it over in your mind. - Anonymous",
"The world is wide, and I will not waste my life in friction when it could be turned into momentum. - Frances E. Willard",
"Believe with all of your heat that you will do what you were made to do. - Orison Swett Marden",
"Do not wait to strike till the iron is hot; but make it hot by striking. - William B. Sprague",
"If you have the guts to keep making mistakes, your wisdom and intelligence leap forward with huge momentum. - Holly Near",
"Good things come to those who wait but greater things come to those who get off their ass and do anything to make it happen. - Anonymous",
"Ask and it will be given to you; search and you will find; knock and the door will be opened for you. - Jesus",
"People often say that motivation doesn’t last. Well, neither does bathing and that is why we recommend it daily. - Zig Ziglar",
"I can, therefore I am. - Simone Weil",
"I’ve found that luck is quite predictable. If you want more luck, take more chances. Be more active. Show up more often. - Brian Tracy",
"You need to overcome the tug of people against you as you reach for high goals. - George S. Patton",
"To know oneself, one should assert oneself. - Albert Camus",
"The first step toward success is taken when you refuse to be a captive of the environment in which you first find yourself. - Mark Caine",
"The most effective way to do it, is to do it. - Amelia Earhart",
"Begin to be now what you will be hereafter. - William James",
"Leap, and the net will appear. - John Burroughs",
"Do your work with your whole heart, and you will succeed – there’s so little competition. - Elbert Hubbard",
"A goal is a dream with a deadline. - Napoleon Hill",
"Things do not happen. Things are made to happen. - John F. Kennedy",
"Quality is not an act, it is a habit. - Aristotle",
"The secret of getting ahead is getting started. - Mark Twain",
"By failing to prepare, you are preparing to fail. - Benjamin Franklin",
"Either you run the day or the day runs you. - Jim Rohn",
"Once you choose hope, anything's possible. - Christopher Reeve",
"Try not to become a person of success, but rather try to become a person of value. - Albert Einstein",
"Success is walking from failure to failure with no loss of enthusiasm. - Winston Churchill",
"Someone is sitting in the shade today because someone planted a tree a long time ago. - Warren Buffett",
"Don't cry because it's over, smile because it happened. - Dr. Seuss",
"Life is short, and it is here to be lived. - Kate Winslet",
"You can't connect the dots looking forward; you can only connect them looking backward...This approach has never let me down, and it has made all the difference in my life. - Steve Jobs",
"Everything you can imagine is real. - Pablo Picasso",
"Successful people do what unsuccessful people are not willing to do. Don't wish it were easier; wish you were better. - Jim Rohn",
"Rarely have I seen a situation where doing less than the other guy is a good strategy. - Jimmy Spithill",
"Change will not come if we wait for some other person or some other time. We are the ones we've been waiting for. We are the change that we seek. - Barack Obama",
"If you love what you do and are willing to do what it takes, it's within your reach. - Steve Wozniak",
"In my experience, there is only one motivation, and that is desire. No reasons or principle contain it or stand against it. - Jane Smiley",
"Keep on going, and the chances are that you will stumble on something, perhaps when you are least expecting it. - Charles F. Kettering",
"The successful warrior is the average man, with laser-like focus. - Bruce Lee",
"In the midst of movement and chaos, keep stillness inside of you. - Deepak Chopra",
"Success does not consist in never making mistakes but in never making the same one a second time. - George Bernard Shaw",
"I don't want to get to the end of my life and find that I lived just the length of it. I want to have lived the width of it as well. - Diane Ackerman",
"As we look ahead into the next century, leaders will be those who empower others. - Bill Gates",
"The only place where success comes before work is in the dictionary. - Vidal Sassoon",
"It’s not what you look at that matters, it’s what you see. - Anonymous",
"The road to success and the road to failure are almost exactly the same. - Colin R. Davis",
"Success is liking yourself, liking what you do, and liking how you do it. - Maya Angelou",
"A real entrepreneur is somebody who has no safety net underneath them. - Henry Kravis",
"The function of leadership is to produce more leaders, not more followers. - Ralph Nader",
"Whenever you find yourself on the side of the majority, it is time to pause and reflect. - Mark Twain",
"If you genuinely want something, don’t wait for it — teach yourself to be impatient. - Gurbaksh Chahal",
"Don’t let the fear of losing be greater than the excitement of winning. - Robert Kiyosaki",
"Motivation is what gets you started. Habit is what keeps you going. - Jim Ryun",
"People rarely succeed unless they have fun in what they are doing. - Dale Carnegie",
"Little minds are tamed and subdued by misfortune; but great minds rise above it. - Washington Irving",
"Knowledge is being aware of what you can do. Wisdom is knowing when not to do it. - Anonymous",
"You can do anything, but not everything. - Anonymous",
"Success is most often achieved by those who don't know that failure is inevitable. - Coco Chanel",
"There are two types of people who will tell you that you cannot make a difference in this world: those who are afraid to try and those who are afraid you will succeed. - Ray Goforth",
"Learn from yesterday, live for today, hope for tomorrow. The important thing is not to stop questioning. - Albert Einstein",
"Take up one idea. Make that one idea your life - think of it, dream of it, live on that idea. Let the brain, muscles, nerves, every part of your body be full of that idea, and just leave every other idea alone. This is the way to success. - Swami Vivekananda",
"You only live once, but if you do it right, once is enough. - Mae West",
"Opportunities don't happen. You create them. - Chris Grosser",
"You miss 100 percent of the shots you don't take. - Wayne Gretzky",
"The way I see it, if you want the rainbow, you gotta put up with the rain. - Dolly Parton",
"The longer I live, the more beautiful life becomes. - Frank Lloyd Wright",
"Success is the sum of small efforts, repeated day-in and day-out. - Robert Collier",
"Things work out best for those who make the best of how things work out. - John Wooden",
"A dream doesn't become reality through magic; it takes sweat, determination, and hard work. - Colin Powell",
"If you always do what interests you, at least one person is pleased. - Katharine Hepburn",
"Twenty years from now you will be more disappointed by the things that you didn't do than by the ones you did do. So throw off the bowlines. Sail away from the safe harbor...Explore. Dream. Discover. - Mark Twain",
"Your work is going to fill a large part of your life, and the only way to be truly satisfied is to do what you believe is great work. - Steve Jobs",
"Don't be afraid to give up the good to go for the great. - John D. Rockefeller",
"Only put off until tomorrow what you are willing to die having left undone. - Pablo Picasso",
"Though no one can go back and make a brand-new start, anyone can start from now and make a brand-new ending. - Carl Bard",
"We become what we think about most of the time, and that's the strangest secret. - Earl Nightingale",
"The biggest risk is not taking any risk...In a world that's changing really quickly, the only strategy that is guaranteed to fail is not taking risks. - Mark Zuckerberg",
"Don't worry about failure; you only have to be right once. - Drew Houston",
"Nothing great was ever achieved without enthusiasm. - Ralph Waldo Emerson",
"Keep your face to the sunshine and you can never see the shadow. - Helen Keller",
"The only place where success comes before work is in the dictionary. - Vidal Sassoon",
"The more you praise and celebrate your life, the more there is in life to celebrate. - Oprah Winfrey",
"All progress takes place outside the comfort zone. - Michael John Bobak",
"The first step toward success is taken when you refuse to be a captive of the environment in which you first find yourself. - Mark Caine",
"I avoid looking forward or backward, and try to keep looking upward. - Charlotte Bronte",
"One of the greatest diseases is to be nobody to anybody. - Mother Teresa",
"Your time is limited, so don’t waste it living someone else’s life. - Steve Jobs",
"Setting goals is the first step in turning the invisible into visible. - Tony Robbins",
"The most difficult thing is the decision to act, the rest is merely tenacity. - Emelia Earhart",
"Courage is grace under pressure. - Ernest Hemingway",
"If you are not willing to risk the usual, you will have to settle for the ordinary. - Jim Rohn",
"There is no easy walk to freedom anywhere, and many of us will have to pass through the valley of the shadow of death again and again before we reach the mountaintop of our desires. - Nelson Mandela",
"It is not the strongest of the species that survive, nor the most intelligent, but the one most responsive to change. - Charles Darwin",
"The best and most beautiful things in the world cannot be seen or even touched -- they must be felt with the heart. - Helen Keller",
"Great minds discuss ideas; average minds discuss events; small minds discuss people. - Eleanor Roosevelt",
"The best revenge is massive success. - Frank Sinatra",
"A successful man is one who can lay a firm foundation with the bricks others have thrown at him. - David Brinkley",
"May you live every day of your life. - Jonathan Swift",
"The difference between winning and losing is most often not quitting. - Walt Disney",
"Live as if you were to die tomorrow. Learn as if you were to live forever. - Mahatma Gandhi",
"I have not failed. I've just found 10,000 ways that won't work. - Thomas Edison",
"When you cease to dream you cease to live. - Malcolm Forbes",
"No one can make you feel inferior without your consent. - Eleanor Roosevelt",
"Failure is another steppingstone to greatness. - Oprah Winfrey",
"Identity is a prison you can never escape, but the way to redeem your past is not to run from it, but to try to understand it, and use it as a foundation to grow. - Jay-Z",
"When I dare to be powerful - to use my strength in the service of my vision, then it becomes less and less important whether I am afraid. - Audre Lorde",
"Develop success from failures. Discouragement and failure are two of the surest stepping stones to success. - Dale Carnegie",
"If you want to make a permanent change, stop focusing on the size of your problems and start focusing on the size of you! - T. Harv Eker",
"If you don’t design your own life plan, chances are you’ll fall into someone else’s plan. And guess what they have planned for you? Not much. - Jim Rohn",
"The number one reason people fail in life is because they listen to their friends, family, and neighbors. - Napoleon Hill",
"There is no chance, no destiny, no fate, that can hinder or control the firm resolve of a determined soul. - Ella Wheeler Wilcox",
"You must expect great things of yourself before you can do them. - Michael Jordan",
"Our greatest fear should not be of failure but of succeeding at things in life that don’t really matter. - Francis Chan",
"In my experience, there is only one motivation, and that is desire. No reasons or principle contain it or stand against it. - Jane Smiley",
"I don’t want to get to the end of my life and find that I lived just the length of it. I want to have lived the width of it as well. - Diane Ackerman",
"Success is...knowing your purpose in life, growing to reach your maximum potential, and sowing seeds that benefit others. - John C. Maxwell",
"Be miserable. Or motivate yourself. Whatever has to be done, it’s always your choice. - Wayne Dyer",
"You’ve got to get up every morning with determination if you’re going to go to bed with satisfaction. - George Lorimer",
"To be successful you must accept all challenges that come your way. You can’t just accept the ones you like. - Mike Gafka",
"Real difficulties can be overcome; it is only the imaginary ones that are unconquerable. - Theodore N. Vail",
"Failure is the condiment that gives success its flavor. - Truman Capote",
"Don’t let what you cannot do interfere with what you can do. - John R. Wooden",
"It is better to fail in originality than to succeed in imitation. - Herman Melville",
"Fortune sides with him who dares. - Virgil",
"You may have to fight a battle more than once to win it. - Margaret Thatcher",
"It's not the size of the dog in the fight, but the size of the fight in the dog - Archie Griffen",
"Nothing lasts forever. Not even your troubles. - Arnold H. Glasgow",
"There are only two ways to live your life. One is as though nothing is a miracle. The other is as though everything is a miracle. - Albert Einstein",
"Where hope grows, miracles blossom. - Elna Rae",
"To accomplish great things, we must not only act, but also dream, not only plan, but also believe. - Anatole France",
"You measure the size of the accomplishment by the obstacles you had to overcome to reach your goals. - Booker T. Washington",
"Most of the important things in the world have been accomplished by people who have kept on trying when there seemed to be no hope at all. - Dale Carnegie",
"Take chances, make mistakes. That's how you grow. Pain nourishes your courage. You have to fail in order to practice being brave - Mary Tyler Moore",
"Being strong means rejoicing in who you are, complete with imperfections - Margaret Woodhouse",
"A life spent making mistakes is not only more honorable but more useful than a life spent doing nothing - George Bernard Shaw",
"If you don’t go after what you want, you’ll never have it. If you don’t ask, the answer is always no. If you don’t step forward, you’re always in the same place - Nora Roberts",
"It took me a long time not to judge myself through someone else's eyes - Sally Field",
"Make the most of yourself, for that is all there is of you - Ralph Waldo Emerson",
"Awards become corroded, friends gather no dust - Jesse Owens",
"Hope never abandons you, you abandon it - George Weinberg",
"Nothing splendid has ever been achieved except by those who dared believe that something inside of them was superior to circumstance - Bruce Barton",
"I quit being afraid when my first venture failed and the sky didn't fall down - Allen H. Neuharth",
"Life is 10% of what happens to me and 90% of how I react to it - John Maxwell",
"Determine never to be idle. No person will have occasion to complain of the want of time who never loses any. It is wonderful how much may be done if we are always doing. - Thomas Jefferson",
"Aerodynamically the bumblebee shouldn't be able to fly, but the bumblebee doesn't know that so it goes on flying anyway - Mary Kay Ash",
"I'm selfish, impatient and a little insecure. I make mistakes, I am out of control and at times hard to handle. But if you can't handle me at my worst, then you sure as hell don't deserve me at my best. - Marilyn Monroe",
"A room without books is like a body without a soul. - Marcus Tullius Cicero",
"Be the change that you wish to see in the world. - Mahatma Gandhi",
"Don't walk behind me; I may not lead. Don't walk in front of me; I may not follow. Just walk beside me and be my friend. - Albert Camus",
"Happiness is a butterfly, which when pursued, is always beyond your grasp, but which, if you will sit down quietly, may alight upon you. - Nathaniel Hawthorne",
"Sometimes you can't see yourself clearly until you see yourself through the eyes of others. - Ellen DeGeneres",
"The whole secret of a successful life is to find out what is one's destiny to do, and then do it. - Henry Ford",
"If you're going through hell, keep going. - Winston Churchill",
"To me, business isn't about wearing suits or pleasing stockholders. It's about being true to yourself, your ideas and focusing on the essentials. - Richard Branson",
"In order to be irreplaceable one must always be different. - Coco Chanel",
"If you're not stubborn, you'll give up on experiments too soon. And if you're not flexible, you'll pound your head against the wall and you won't see a different solution to a problem you're trying to solve. - Jeff Bezos",
"If you can't explain it simply, you don't understand it well enough. - Albert Einstein",
"You can't please everyone, and you can't make everyone like you. - Katie Couric",
"I believe every human has a finite number of heartbeats. I don't intend to waste any of mine. - Neil Armstrong",
"The two most important days in your life are the day you are born and the day you find out why. - Mark Twain",
"As you grow older, you will discover that you have two hands, one for helping yourself, the other for helping others. - Audrey Hepburn",
"If you want to achieve excellence, you can get there today. As of this second, quit doing less-than-excellent work. - Thomas J. Watson",
"If your actions inspire others to dream more, learn more, do more, and become more, you are a leader. - John Quincy Adams",
"You may only succeed if you desire succeeding; you may only fail if you do not mind failing. - Philippos",
"I find that the harder I work, the more luck I seem to have. - Thomas Jefferson",
"It often requires more courage to dare to do right than to fear to do wrong. - Abraham Lincoln",
"I find that when you have a real interest in life and a curious life, that sleep is not the most important thing. - Martha Stewart",
"Success does not consist in never making mistakes but in never making the same one a second time. - George Bernard Shaw",
"Knowledge is being aware of what you can do. Wisdom is knowing when not to do it. - Anonymous",
"You can do anything, but not everything. - Anonymous",
"There are two types of people who will tell you that you cannot make a difference in this world: those who are afraid to try and those who are afraid you will succeed. - Ray Goforth",
"Things work out best for those who make the best of how things work out. - John Wooden",
"If you are not willing to risk the usual, you will have to settle for the ordinary. - Jim Rohn",
"Learn from yesterday, live for today, hope for tomorrow. The important thing is not to stop questioning. - Albert Einstein",
"Opportunities don't happen. You create them. - Chris Grosser",
"There is no easy walk to freedom anywhere, and many of us will have to pass through the valley of the shadow of death again and again before we reach the mountaintop of our desires. - Nelson Mandela",
"It is not the strongest of the species that survive, nor the most intelligent, but the one most responsive to change. - Charles Darwin",
"Great minds discuss ideas; average minds discuss events; small minds discuss people. - Eleanor Roosevelt",
"A successful man is one who can lay a firm foundation with the bricks others have thrown at him. - David Brinkley",
"No one can make you feel inferior without your consent. - Eleanor Roosevelt",
"Don't limit yourself. Many people limit themselves to what they think they can do. You can go as far as your mind lets you. What you believe, remember, you can achieve. - Mary Kay Ash",
"Be who you are and say what you feel, because those who mind don't matter and those who matter don't mind. - Dr. Seuss",
"Keep your eyes on the stars and your feet on the ground. - Theodore Roosevelt",
"The only person you should try to be better than is the person you were yesterday. - Anonymous",
"Never be bullied into silence. Never allow yourself to be made a victim. Accept no one's definition of your life; define yourself. - Harvey Fierstein",
"A man who flies from his fear may find that he has only taken a shortcut to meet it. - Sador, Children of Húrin",
"Life's too mysterious to take too serious. - Mary Engelbreit",
"The woman who follows the crowd will usually go no further than the crowd. The woman who walks alone is likely to find herself in places no one has been before. - Albert Einstein",
"There isn't a way things should be. There's just what happens, and what we do. - Terry Pratchett, A Hat Full of Sky",
"It's not about how hard you can hit; it's about how hard you can get hit and keep moving forward. - Rocky Balboa, Rocky",
"If you want to go fast, go alone. If you want to go far, go together. - African proverb",
"Believe you can and you're halfway there. - T. Roosevelt",
"Plant your garden and decorate your own soul, instead of waiting for someone to bring you flowers. - Jose Luis Borges",
"Do not go where the path may lead, go instead where there is no path and leave a trail. - Ralph Waldo Emerson",
"Always do your best. What you plant now, you will harvest later. - Og Mandino"
];

// Get random phrase
var random = nicePhrases[Math.floor(Math.random() * nicePhrases.length)];
// console.log(random);

document.getElementById("rathernice").textContent = random.toString();
